version: '3'
services:
  restart: always
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
